language: java
jdk:
  - oraclejdk8
before_install:
  - ant clean-all
  - ant -v js.minify
  - ant -v css.minify
install: ant compile
script: ant test
notifications:
  email:
    recipients:
      - npm.mcmahon@gmail.com
    on_success: always
    on_failure: always

